# Generated by Django 5.0.4 on 2024-04-14 09:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone_number', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=255)),
                ('registration_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.IntegerField()),
                ('date_added', models.DateTimeField()),
                ('image', models.ImageField(blank=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('order_date', models.DateTimeField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopapp.customer')),
                ('products', models.ManyToManyField(to='shopapp.product')),
            ],
        ),
        migrations.AddField(
            model_name='customer',
            name='ordered_items_last_month',
            field=models.ManyToManyField(related_name='ordered_items_last_month', to='shopapp.product'),
        ),
        migrations.AddField(
            model_name='customer',
            name='ordered_items_last_week',
            field=models.ManyToManyField(related_name='ordered_items_last_week', to='shopapp.product'),
        ),
        migrations.AddField(
            model_name='customer',
            name='ordered_items_last_year',
            field=models.ManyToManyField(related_name='ordered_items_last_year', to='shopapp.product'),
        ),
    ]
